version: '3.4'

services:
  bzz-os-app005:
    build: bzz-app001
    image: bzznew/bzz-os-app005:latest
    stdin_open: true
    env_file:
      - .env
      - bzz-app001/.env
    ports:
      - '8001:8000'
    volumes:
      - '/app/node_modules'
      - '/home/files_app2/HIMS2/SmartApp/OS:/home/node'
    environment:
      DB_SERVER: 45.33.48.152
      DB_PORT: 1456
      DB_NAME: 'HIMSOS'
      DB_USERNAME: sa
      DB_PASSWORD: MoonPie1
      PORT: 8000
      JWT_SCHEME: jwt
      JWT_TOKEN_PREFIX: Bearer
      JWT_SECRET: thiscanbechangedlater123654789
      JWT_TOKEN_EXPIRATION: 18000000
      JWT_TOKEN_HASH_ALGO: SHA-256
      SECRET: hackthoon
      KEY: bzzdev
    links:
      - nats.service
    depends_on:
      - nats.service
#      - mssql

  nats.service:
    image: nats
