export default {
    font: [
        'Arial', 
        'Georgia', 
        'Impact', 
        'Tahoma', 
        'Times New Roman', 
        'Verdana', 
        'Are You Serious',
        'Cookie',
        'Lobster Two',
        'Merienda',
        'Fruktur', 
        'Irish Grover', 
        'Dancing Script',
        'Architects Daughter',
        'Henny Penny', 
        'Shadows Into Light', 
        'Cormorant Garamond',
        'Permanent Marker',
        'Alumni Sans', 
        'Satisfy', 
        'Festive', 
        'Cinzel', 
        'Courgette', 
        'Rampart One', 
        'Parisienne',
        'Special Elite', 
        'Eczar',
        'Rubik Beastly', 
        'Birthstone Bounce', 
        'Grechen Fuemen', 
        'Grey Qo', 
        'Creepster', 
        'Bangers', 
        'Carattere', 
        'Rock Salt', 
        'Alex Brush',
        'Cherish',
        'IM Fell English SC', 
        'Explora',
        'Aclonica',
        'Shadows Into Light Two', 
        'Black Ops One', 
        'Ephesis',
        'Annie Use Your Telescope', 
        'Berkshire Swash', 
        'Niconne',
        'Fredericka the Great',
        'Cinzel Decorative', 
        'Rye',
        'Kristi', 
        'Nixie One',
        'Allison',
        'Bungee Inline',
        'Qwigley',
        'Happy Monkey',
        'Emilys Candy',
        'Frijole',
        'Vast Shadow', 
        'Bungee Shade',
        'Codystar', 
        'Shojumaru',
        'Ruslan Display', 
        'Nosifer', 
        'New Rocker', 
        'Londrina Outline',
        'Bigelow Rules',
        'Piedra',
        'Eagle Lake',
        'Playfair Display', 
        'Langar', 
        'Xanh Mono',
        'BioRhyme Expanded',
        'Long Cang', 
        'Snowburst One',
        'Sedgwick Ave Display',
        'Almendra Display'
      ].sort(),
    buttonList: [
        ['undo', 'redo', 'font', 'fontSize'],
        ['bold', 'underline', 'italic', 'strike'],
        ['fontColor', 'hiliteColor', 'textStyle'],
        ['align', 'horizontalRule', 'list', 'lineHeight'],
        ['image', 'table']
       ] 
} 